export const START = 'START'
export const DONE = 'DONE'
export const PAUSE = 'PAUSE'
export const RESUME = 'RESUME'
export const CLOSE = 'CLOSE'
export const COUNTDOWN = 'COUNTDOWN'
export const ADDTIME = 'ADDTIME'